name: bazarse
description: AI Bazar
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0

  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1

  # Video & Media
  video_player: ^2.8.1
  chewie: ^1.7.4

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8

  # HTTP & Storage
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/videos/
    - assets/videos/homescreen/
    - assets/icon/
